POST https://group-project-gwdp-monday-12pm.onrender.com/api/auth/login 
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "123"
}

############
GET http://localhost:5000/api/watchlists/670b6415a122b53e7c4b6aaf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBiYzM3YjViODI1NWQwZjQwNTA0NjkiLCJpYXQiOjE3Mjg4MzI5NDAsImV4cCI6MTcyODgzNjU0MH0.izQANjUgZQD0uytuNPO9cnUB65RdqQPuax7FNo4vAeY

############
POST http://localhost:5000/api/auth/register 
Content-Type: application/json

{
    "name": "123",
    "email": "123@gmail.com",
    "password": "123"
}

#########

GET https://group-project-gwdp-monday-12pm.onrender.com/api/auth/user 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBiYzM3YjViODI1NWQwZjQwNTA0NjkiLCJpYXQiOjE3Mjg4MzI5NDAsImV4cCI6MTcyODgzNjU0MH0.izQANjUgZQD0uytuNPO9cnUB65RdqQPuax7FNo4vAeY
