POST http://localhost:5000/api/auth/login 
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "123"
}

############
GET http://localhost:5000/api/watchlists/670b6415a122b53e7c4b6aaf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBiNjQxNWExMjJiNTNlN2M0YjZhYWQiLCJpYXQiOjE3Mjg3OTk5ODUsImV4cCI6MTcyODgwMzU4NX0.n5sgRcbBPJ8UH4MrZfiSY0CCnSTROnzvMcX1vMy46C4